### ISSUE TITLE
Batch-edit function

### ISSUE THREAD

**Issue by DBinaghi** [BGSU-LITS/omeka-plugin-SelectOwner#1]
Hello.

This is a very good work, thanks.

IMHO, this plugin could be even more useful if it allowed batch-edit case, at least for **Items** (I don't think there would be any need to change ownership of several **Collections** at the same time): potentially, an admin/superuser might want to add several **Items** at the same time (for instance, using CSVImport or Dropbox plugins), but then let contributors fill in the metadata. Batch-changing their ownership could then save a lot of time.

I would also try to merge your work with some ideas in https://github.com/patrickmj/ReassignOwnership/blob/master/ReassignOwnershipPlugin.php, as Patrick is considering some extra checks (like record existence and user role); and it makes more sense that it's called Reassign Ownership, as Ownership is already set when adding the new **Item**.

Finally, I would not change the ACL in this plugin, as the search for Items is not relevant to this topic.

If it can help, I already coded how to add the combobox to the batch-edit page:
```
public function hookAdminItemsBatchEditForm($args) {
        $this->_echoBatchPanel($args);
}

private function _echoBatchPanel($args) {
        $view = $args['view'];
        $record = $args['record'];
        $user = current_user();
        echo "<div id='reassign_ownership-form' class='field'>";
        echo "<label class='two columns alpha' for='reassign_ownership_id'>" . __('Reassign Ownership') .  "</label>";
        echo "<div class='inputs five columns omega'>";
        $ownershipOptions = get_table_options('User', null, array('sort_field' => 'name'));
        $ownershipOptions = array('' => __('Select Below')) + $ownershipOptions;
        echo $view->formSelect('reassign_ownership_id', null, array(), $ownershipOptions);
        echo "</div>";
        echo "</div>";
}
```

**Comment by kloor** [comment]
If you work out the batch editing, I would accept a pull request.

I was likely unaware of Patrick's plugin when I initially developed this. I don't see any advantage to the additional checks as you already need permissions to edit the item or collection for the form to be displayed. I also see no point in renaming this plugin. Feel free to use Patrick's if you prefer those differences.

I see the ACL change as being related to the purpose of this plugin, to not only allow the owner of an item or collection to be changed, but also to display who is the owner and allow all users to search for items by user. This fits our use case in developing the plugin.

**Comment by DBinaghi** [comment]
Hello, kloor.

Thanks to a tip from "magic" John, the batch-edit function is now implemented, as you can see from the https://forum.omeka.org/t/help-needed-changing-reassignownership-plugin-to-include-batch-edit thread. I've gone on with Patrick's plugin as it matched more my needs, but please feel free to use the batch-edit extension in your plugin too if it works for you.

All the best, and thanks again for your help.
